# Generated by Django 3.1.1 on 2020-09-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_status',
            field=models.BooleanField(default=False),
        ),
    ]
