# Generated by Django 3.1.1 on 2020-09-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramide', '0002_game_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='drinks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
