# Generated by Django 3.1.1 on 2020-09-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramide', '0003_auto_20200919_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_room',
        ),
        migrations.AlterField(
            model_name='player',
            name='drinks',
            field=models.IntegerField(default=0),
        ),
    ]
