# Generated by Django 3.1.1 on 2020-09-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramide', '0005_auto_20200921_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
