# Generated by Django 3.1.1 on 2020-09-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramide', '0006_auto_20200921_2209'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='unique_player'),
        ),
    ]
