# Generated by Django 3.1.1 on 2020-09-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramide', '0007_auto_20200921_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deckNum',
            field=models.IntegerField(default=1),
        ),
    ]
