# Generated by Django 3.1.1 on 2020-09-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='eleccion',
        ),
    ]
