# Generated by Django 3.1.1 on 2020-09-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200911_0004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eleccion',
            new_name='Choice',
        ),
    ]
